### ISSUE TITLE
EventLoop doesn't provide Reader a way to terminate execution elegantly

### ISSUE THREAD

**Issue by benkrikler** [alphatwirl/alphatwirl#14] opened 2017-11-22 09:30 UTC
### Problem
The code in the [EventLoop class](https://github.com/alphatwirl/alphatwirl/blob/v0.9.x/alphatwirl/loop/EventLoop.py#L25-L33) handles the reader (typically a composite reader) and provides it with events from the tree(s) by:
1. Call `reader.begin()` method
2. For each event:
    a. Call `reader.event()`
3. Call `reader.end()`

In each case, the return of each of `reader`'s methods is ignored.  This makes it awkward for a reader to tell the event loop to terminate early, or not run at all in the case of `begin()`. `begin()` can raise an exception of course, but in some cases that is more extreme than really needed.

### Solution
Have the return of each calll to reader `begin`, `event`, and `end` checked, and execution halted if the return does not evaluate to true.

### Specific example
I'm running over a large heppy dataset and including the existing RA1 AlphaTools sequence as a single Reader.  The heppy dataset is being split up using AlphaTwirl and submitted to the Bristol htcondor batch system.  One of the datasets in this input is not supposed to be handled by AlphaTools and AlphaTools knows this, so it would normally just ignore it, however this causes an exception to be raised crashing the batch job, which is then re-submitted.  To enable things to finish elegantly, I would prefer to be able to signal to the EventLoop that this jobs should not proceed in the `begin()` method of the reader that wraps AlphaTools.

**Comment by TaiSakuma** [comment] 2017-11-22 10:28
That is an interesting point.

Can you point me to the single Reader mentioned in Specific example?

The return code of `event()` is already used for event selection. For example in `ReaderComposite`:
https://github.com/alphatwirl/alphatwirl/blob/4948d49794636c64865a87457bd44f50029a6256/alphatwirl/loop/ReaderComposite.py#L36-L38
also classes in [basic.py]( https://github.com/alphatwirl/alphatwirl/blob/4948d49794636c64865a87457bd44f50029a6256/alphatwirl/selection/modules/basic.py).

If `event()` returns `False`, that means the reader rejects the event. It doesn't mean that the reader cannot read any more events. 

Neither of the return codes of `begin()` or `end()` is used. 

Your suggestion implies that a reader doesn't always begin with `begin()` but can decide not to read any events. I would like to understand why that happens. Why is the `eventLoop` called at first place?

**Comment by TaiSakuma** [comment] 2018-01-05 10:01
@benkrikler, is this still an issue? can you point me to the example you mentioned?

**Comment by benkrikler** [comment] 2018-01-08 10:18
Hi Tai,  I don't believe we've changed the code in the EventLoop class to inspect the return value from the reader's `begin`, `event` or `end` methods (looking at code here: https://github.com/alphatwirl/alphatwirl/blob/master/alphatwirl/loop/EventLoop.py#L28-L32), so in that sense this is still an unsolved issue. 

What do you mean by "point me to the example"?  There's not much code to show because it's a specific example that illustrates one use case where this issue is a problem.

**Comment by TaiSakuma** [comment] 2018-01-08 11:42
I know the code hasn't been changed. I wanted to ask if the issue is still causing a problem.

I don't understand the problem well.

You described an example in the section of "Specific example". Can I see the code for the example? That might help me understand the problem.

Or if it is no longer causing a problem, we can close this issue.

**Comment by TaiSakuma** [comment] 2018-01-11 13:01
I will close this issue eventually maybe in a few week unless I see the example code or more detailed explanation of the problem.

I can think of some situations where the proposed solution is a possible solution, but not any situations where the proposed solution is an elegant solution.

If I understand the problem well, I might be able to understand the proposed solution or suggest other solutions.

**Closed** 2018-02-04 13:14 UTC
